### ISSUE TITLE
Solution 15 - Confusing naming between sp to sso1 and sp1 to sso2

### ISSUE THREAD

**Issue by lloyd-delacroix** [f5devcentral/access-solutions#162]
Some configurations are created under the name "sp" and bound to "sso1" and then "sp1" bound to "sso2". It makes it harder to follow along than if "sp1" and "sp2" were used instead to match directly.

**Comment by yahshun** [comment]
Will provide a mapping table between SP and IDP bindings.  This should elevate any confusion.
