### ISSUE TITLE
Solution1 is missing instructions for using the VPN from a user's perspective

### ISSUE THREAD

**Issue by boreal321** [f5devcentral/access-solutions#8]
As discussed in the Teams chat:

[2:55 PM] Victor Granic
is there supposed to be any content under the heading "The Policy from a user’s perspective"?

[2:56 PM] Victor Granic
    this is for solution1
​
[3:14 PM] Victor Granic
    there's no guidance on how to test the VPN, specifically which user to log in as. i logged in using user1 to poke around. do you think we should have another section on logging in using the accounts in AD?

​[3:15 PM] Jason Wilburn
    Yes. That was the goal.  To show how things work.  
​
[3:16 PM] Jason Wilburn
    Thank for the input.  We need to say something like go to solution1.acmec.com and login as user1. etc.....
​
[3:17 PM] Victor Granic
    right, that's what i was thinking but then you know, dummy syndrome set in and i thought maybe i just gotta be smarter about this and figure  stuff out
​
[3:18 PM] Victor Granic
    ok so i'll leave that content to you guys or would you like me to create it? and if so, let me know what you had in mind.
​
[3:18 PM] Jason Wilburn
    no. you're right.  That's why we want folks to test.  Chas and I are too close to to it at this point to accurately test

​[3:18 PM] Jason Wilburn
    feel free to creat it if you want to.  Or just put it on the list  of things to fix

**Comment by yahshun** [comment]
User's perspective added
